<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BojanMiron_orarend [
<!ELEMENT BojanMiron_orarend (ora+)>
<!ELEMENT ora (targy?, idopont?, helyszin?, oktato?, szak?)>
<!ELEMENT idopont (nap+,tol?,ig?)>
<!ELEMENT  targy(#PCDATA)>
<!ELEMENT  nap(#PCDATA)>
<!ELEMENT  tol(#PCDATA)>
<!ELEMENT  ig(#PCDATA)>
<!ELEMENT  helyszin(#PCDATA)>
<!ELEMENT  oktato(#PCDATA)>
<!ELEMENT  szak(#PCDATA)>

<!ATTLIST ora id CDATA #REQUIRED>
<!ATTLIST ora tipus CDATA #IMPLIED>

]>
<BojanMiron_orarend>
    
    <ora id="1" tipus="Előadás">
        <targy>Aatkezelés XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10:00</tol>
            <ig>11:30</ig>
        </idopont>
        <helyszin>A13 terem</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="1" tipus="Gyakorlat">
        <targy>Adatkezelés XML_ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>13:30</ig>
        </idopont>
        <helyszin>A13 terem</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    
    <ora id="2" tipus="Előadás">
        <targy>Mesterséges intelligencia alapjai</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>11:30</ig>
        </idopont>
        <helyszin>XXXII. Előadó</helyszin>
        <oktato>Fazekas Levente</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="2" tipus="Gyakorlat">
        <targy>Mesterséges intelligencia alapjai</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>16:00</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>XXXII. Előadó</helyszin>
        <oktato>Fazekas Levente</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    
</BojanMiron_orarend>
